name: Git Release Creator
on:
  push:
    tags:
      - 'v*'

jobs:
  git-release-creation:
    name: akeyless-github-action-git-release-creation
    runs-on: ubuntu-20.04
    steps:
      - name: Check out akeyless-github-action code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: true #false
          prerelease: false